config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  root 'home#index'
  resources :users
  resource :attendance, only: [:new, :create]
  resource :absence, only: [:new]

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user
  validates :present, presence: true
  validate :check_for_duplicates, if: [:user]

  private
  def check_for_duplicates
    last_entered_attendance = Attendance.select(:created_at, :present).where(user: user, present: true).last
    today = Date.today
    if last_entered_attendance.present? && last_entered_attendance.created_at.at_beginning_of_day <= today
        errors[:base] << "Already Entered Attendance for Today"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, length: { minimum: 2 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
    @users = User.all
  end

  def create
    @present = true
    @date = DateTime.now
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    find_user_attendance
  end

  protected
  def find_user_attendance
    @user_attendance = Attendance.group(:user_id).count
  end
end

# =select_date(Time.now,month,day,year)

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attendances/create.html.haml
<h1>Attendance#create</h1>
<p>Find me in app/views/attendance/create.html.erb</p>

app/views/attendances/new.html.haml
%h1 Attendance
%select#student
    - @users.each do |user|
        %option #{user.name}
= link_to "Present", attendance_path, method: :post

app/views/home/index.html.haml
- if @user_attendance.empty?
  = @user_attendance
  %p There isn't any recorded attendance yet.  You should record yours!
- else
  %h1 Attendance Leaderboard
= link_to "Record Attendance", new_attendance_path
= link_to "Record Future Absence", new_absence_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NssAttendance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>